package ca.ualberta.odobot.guidance.connectionmanagers;

import ca.ualberta.odobot.common.Utils;
import ca.ualberta.odobot.guidance.GuidanceVerticle;
import ca.ualberta.odobot.guidance.OdoClient;
import ca.ualberta.odobot.guidance.execution.ExecutionRequest;
import ca.ualberta.odobot.guidance.execution.ResourceParameter;
import ca.ualberta.odobot.guidance.execution.SchemaParameter;
import ca.ualberta.odobot.guidance.instructions.Instruction;
import ca.ualberta.odobot.logpreprocessor.LogPreprocessor;
import ca.ualberta.odobot.semanticflow.navmodel.NavPath;
import ca.ualberta.odobot.snippet2xml.SemanticObject;
import ca.ualberta.odobot.snippet2xml.Snippet2XMLService;
import ca.ualberta.odobot.snippet2xml.Snippet2XMLVerticle;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

import static ca.ualberta.odobot.semanticflow.Utils.computeXpathNoRoot;

public class GuidanceConnectionManager extends AbstractConnectionManager implements ConnectionManager {

    private static final Logger log = LoggerFactory.getLogger(GuidanceConnectionManager.class);
    private static final String SOURCE = "GuidanceConnectionManager";
    private Map<String, Promise> activePromises = new LinkedHashMap<>();

    public long timeoutTimer = -1l;

    public GuidanceConnectionManager(OdoClient client){
        super(client);
    }

    public void onMessage(JsonObject message){
        switch (message.getString("type")){
            case "NAVIGATION_OPTIONS_SHOW_RESULT":
                Promise promise = activePromises.get("NAVIGATION_OPTIONS_SHOW_RESULT");
                promise.complete(message);
                activePromises.remove("NAVIGATION_OPTIONS_SHOW_RESULT");
                break;
            case "PATH_COMPLETE_ACK":
                activePromises.get("PATH_COMPLETE_ACK").complete(message);
                activePromises.remove("PATH_COMPLETE_ACK");
                break;
            case  "EXECUTION_RESULT":
                activePromises.get("EXECUTION_RESULT").complete(message);
                activePromises.remove("EXECUTION_RESULT");

                break;

            case "UNRESOLVABLE_XPATH":
                log.info("OdoX reported unresolvable xpath: {} from instruction generated by path node: {}. Attempting to back-track and recover.", message.getString("xpath"), message.getString("sourceNodeId"));
                var failedNodeId = message.getString("sourceNodeId");

                client.getRequestManager().recoverFromFailedNode(failedNodeId);


                break;
            case "REGISTER_ALTERNATE_XPATH":
                //During the execution of certain instructions, the exact xpath sent to OdoX by the server might differ from the one OdoX had to use to actually execute the instruction.
                //When this happens, we add the new xpath OdoX used to the corresponding instruction so that the RequestManager#instructionWatcher can properly identify that the expected instruciton was executed.
                //TODO: eventually, these new xpaths should be merged into the nav model.
                String alternateXpath = message.getString("alternateXpath");
                String sourceNodeId = message.getString("sourceNodeId");

                log.info("Attempting to register alternate xpath: {} for sourceNodeId: {}", alternateXpath, sourceNodeId);
                Optional<Instruction> _instruction = client.getRequestManager().getNavPaths().stream().map(NavPath::lastInstruction)
                        .filter(lastInstruction -> lastInstruction.getSourceNodeId().equals(sourceNodeId))
                        .findAny();

                if(_instruction.isPresent()){
                    _instruction.get().addAlternateXpath(alternateXpath);
                    log.info("Successfully registered alternate xpath: {}", alternateXpath);
                }

                JsonObject confirmation = new JsonObject()
                        .put("type", "ALTERNATE_XPATH_CONFIRMED")
                        .put("source", SOURCE)
                        .put("pathsRequestId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                        .put("alternateXpath", alternateXpath); //Confirm which xpath was registered.
                send(confirmation);

                break;
        }
    }

    public Future<JsonObject> clearNavigationOptions(){
        JsonObject clearNavigationOptionsRequest = new JsonObject()
                .put("type", "CLEAR_NAVIGATION_OPTIONS")
                .put("source", SOURCE)
                .put("pathsRequestId", client.getRequestManager().getActiveExecutionRequest().getId().toString());

        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("CLEAR_NAVIGATION_OPTIONS_RESULT", promise);

        send(clearNavigationOptionsRequest);

        return promise.future();
    }

    public Future<JsonObject> notifyPathComplete(){
        JsonObject notifyPathCompleteRequest = makeNotifyPathCompleteRequest(SOURCE);
        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("PATH_COMPLETE_ACK", promise);

        send(notifyPathCompleteRequest);
        return promise.future();
    }

    public Future<JsonObject> showNavigationOptions(JsonObject navigationOptions){
        JsonObject showNavigationOptionsRequest = new JsonObject()
                .put("type", "SHOW_NAVIGATION_OPTIONS")
                .put("source", SOURCE)
                .put("pathsRequestId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                .mergeIn(navigationOptions);

        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("NAVIGATION_OPTIONS_SHOW_RESULT", promise);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        send(showNavigationOptionsRequest);

        return promise.future();
    }

    public Future<JsonObject> sendExecutionInstruction(JsonObject instruction){

        //Reset the timeout timer.
        if(timeoutTimer != -1l){ //Only if it hasn't yet been set.
            GuidanceVerticle._vertx.cancelTimer(timeoutTimer);
        }

        GuidanceVerticle._vertx.setTimer(client.getRequestManager().getActiveExecutionRequest().getTimeout(), id->{
            timeoutTimer = id;
            log.info("Task execution timed out!");
            client.getRequestManager().getEvaluationComplete().tryFail("Timeout!");
        });

        JsonObject executionRequest = new JsonObject()
                .put("type", "EXECUTE")
                .put("source", SOURCE)
                .put("executionId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                .mergeIn(instruction);

        Promise<JsonObject> promise = Promise.promise();

        if(executionRequest.getString("action").equals("getDOMSnapshot")){
            log.info("Configuring handling for getDOMSnapshot instruction.");

            //GetDOMSnapshot is an instruction that returns a snapshot of the current DOM from OdoX.
            //We send this instruction to resolve resource parameters. When we have a click instruction that is meant to click on a particular kind of resource
            //we first get the DOM snapshot and find all <a> tags linking to that kind of resource on the page. Each such <a> tag is an option for the LLM to consider in the context
            //of the task being executed.
            promise.future()
                    .onFailure(err->{
                        log.error("Error while handling getDOMSnapshot instruction result.");
                        log.error(err.getMessage(), err);
                    })
                    .onSuccess(response->{
                log.info("Handling getDOMSnapshot result");

                String domSnapshot = response.getString("domSnapshot");
                String sourceNodeId = response.getString("sourceNodeId");

                Snippet2XMLVerticle.sqliteService.getNormalizedHrefsByLabel(executionRequest.getString("parameterName"))
                        .compose(labelHrefs -> {

                            //labelHrefs are a set of normalized href values that correspond with this parameter label.
                            //So our next job is to identify all <a> tags whose 'href' attribute values, after normalization match any of the hrefs in the set labelHrefs.
                            Document document = Jsoup.parse(domSnapshot);

                            List<Element> options = new ArrayList<>();

                            document.selectXpath("//a")
                                    .stream()
                                    .filter(aTag -> aTag.hasAttr("href"))
                                    .forEach(aTag->{
                                String normalizedHref = Utils.normalizeBaseUri(aTag.attr("href"));

                                if(labelHrefs.contains(normalizedHref)){
                                    options.add(aTag);
                                }
                            });

                            List<JsonObject> optionsData = options.stream()
                                    .map(element-> new JsonObject()
                                                .put("html", element.outerHtml())
                                                .put("xpath", computeXpathNoRoot(element))
                                    ).toList();

                            ExecutionRequest request = client.getRequestManager().getActiveExecutionRequest();

                            return Future.all(
                                    Snippet2XMLVerticle.snippet2XML.pickResourceParameterValue(optionsData, ((ResourceParameter)request.getParameter(executionRequest.getString("parameterId"))).getQuery()),
                                    Future.succeededFuture(document)
                            );




                        }).onSuccess(compositeFuture->{

                            JsonObject pickedValue = (JsonObject) compositeFuture.list().get(0);
                            Document document = (Document) compositeFuture.list().get(1);


                            Element selectedOption = document.selectXpath(pickedValue.getString("xpath")).get(0);
                            String selectedOptionXpath = pickedValue.getString("xpath");

                            JsonObject clickRequest = new JsonObject()
                                    .put("type", "EXECUTE")
                                    .put("source", SOURCE)
                                    .put("executionId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                                    .put("action", "click")
                                    .put("xpath", selectedOptionXpath)
                                    .put("sourceNodeId", sourceNodeId);

                            activePromises.put("EXECUTION_RESULT", Promise.promise());
                            try {
                                Thread.sleep(1000);
                            }catch (InterruptedException e){
                                throw new RuntimeException(e);
                            }
                            send(clickRequest);
                        })
                        .onFailure(err->{
                            log.error("Error while handling getDOMSnapshot");
                            log.error(err.getMessage(), err);
                        });
            });
        }

        if(executionRequest.getString("action").equals("queryDom")){
            //queryDom requests will respond with a bunch of HTML elements, from which we need to pick one to convert to a click action.

            promise.future().onSuccess(response->{

                String sourceNodeId = executionRequest.getString("sourceNodeId");

                List<JsonObject> queryResults = response.getJsonArray("queryResults").stream().map(o->(JsonObject)o).collect(Collectors.toList());

                //If the query failed to find any candidates for OdoBot to consider clicking on, try recovering by recomputing a new path avoiding the node that prompted this.
                if (queryResults.isEmpty()){
                    client.getRequestManager().recoverFromFailedNode(sourceNodeId);
                    return;
                }

                log.info("Last result: \n{}", queryResults.get(queryResults.size()-1).getString("html"));

                if(!executionRequest.containsKey("parameterId")){
                    Snippet2XMLVerticle.snippet2XML.pickValue(queryResults, client.getRequestManager().getActiveExecutionRequest().getTaskDescription())
                            .onSuccess(option->{
                                log.info("Picked option: {}", option);
                                JsonObject clickRequest = new JsonObject()
                                        .put("type", "EXECUTE")
                                        .put("source", SOURCE)
                                        .put("executionId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                                        .put("action", "click")
                                        .put("xpath", option.getString("xpath"));

                                activePromises.put("EXECUTION_RESULT", Promise.promise());
                                //Log how this query dom operation went for debugging, troubleshooting and sanity checking.
                                saveQueryDomResult(client, executionRequest, response.getJsonArray("queryResults"), sourceNodeId, clickRequest);
                                try{
                                    Thread.sleep(1000);
                                }catch (InterruptedException e){
                                    throw new RuntimeException(e);
                                }
                                send(clickRequest);
                            })
                            .onFailure(err->{
                                log.error("Error while handling queryDom execution result!");
                                log.error(err.getMessage(), err);
                            });
                }else{
                    String schemaId = LogPreprocessor.neo4j.getSchemaId(executionRequest.getString("parameterId"));

                    Snippet2XMLVerticle.sqliteService.getSemanticSchemaById(schemaId)
                            .compose(schema -> {
                                return Future.join(
                                        queryResults.stream()
                                                .map(html->Snippet2XMLVerticle.snippet2XML.getObjectFromHTMLIgnoreSchemaIssues(html.getString("html"), schema).compose(semanticObject -> {
                                                    return Future.succeededFuture(new JsonObject().put("semanticObject", semanticObject.toJson()).put("xpath", html.getString("xpath")));
                                                }, err->Future.succeededFuture(null)))
                                                .collect(Collectors.toList())
                                );
                            })
                            .compose(compositeFuture -> {
                                List<JsonObject> objects = compositeFuture.list().stream()
                                        .filter(Objects::nonNull) //It's possible some html will fail to resolve to proper xml objects.
                                        .map(o->(JsonObject)o).collect(Collectors.toList());

                                Map<String, String> objectMap = new HashMap<>();
                                objects.forEach(object->{
                                    SemanticObject semanticObject = new SemanticObject(object.getJsonObject("semanticObject"));
                                    objectMap.put(semanticObject.getObject(), object.getString("xpath"));
                                });

                                List<SemanticObject> options = objects.stream().map(json->new SemanticObject(json.getJsonObject("semanticObject"))).collect(Collectors.toList());

                                ExecutionRequest request = client.getRequestManager().getActiveExecutionRequest();

                                return Snippet2XMLVerticle.snippet2XML.pickParameterValue(options, ((SchemaParameter)request.getParameter(executionRequest.getString("parameterId"))).getQuery())
                                        //Resolve the picked semantic object to its corresponding xpath...
                                        .compose(semanticObject -> Future.succeededFuture(objectMap.get(semanticObject.getObject())))
                                        ;

                            })
                            .onSuccess(option->{
                                log.info("Picked option: {}", option);
                                JsonObject clickRequest = new JsonObject()
                                        .put("type", "EXECUTE")
                                        .put("source", SOURCE)
                                        .put("executionId", client.getRequestManager().getActiveExecutionRequest().getId().toString())
                                        .put("action", "click")
                                        .put("xpath", option);

                                activePromises.put("EXECUTION_RESULT", Promise.promise());

                                try{
                                    Thread.sleep(1000);
                                }catch (InterruptedException e){
                                    throw new RuntimeException(e);
                                }
                                send(clickRequest);
                            })
                            .onFailure(err->{
                                log.error("Error while handling queryDom execution result!");
                                log.error(err.getMessage(), err);
                            })
                    ;
                }



            });


        }

        activePromises.put("EXECUTION_RESULT", promise);
        try{
            Thread.sleep(3000);
        }catch (InterruptedException e){
            throw new RuntimeException(e);
        }
        send(executionRequest);

        return promise.future();
    }

    private static void saveQueryDomResult(OdoClient client, JsonObject executionRequest, JsonArray queryResults, String sourceNodeId, JsonObject clickRequest){
        String filename = "./%s/%s-query-dom-%s.txt".formatted("execution_events", client.getRequestManager().getEvalId(),sourceNodeId).replaceAll("\\|","-");
        File fout = new File(filename);
        try(FileWriter fw = new FileWriter(fout);
            BufferedWriter bw = new BufferedWriter(fw);
        ){
            StringBuilder sb = new StringBuilder();
            sb.append("Source Node ID: %s\n".formatted(sourceNodeId));
            sb.append("Cypher Query:\nMATCH (n) where n.id = '%s' RETURN n;\n".formatted(sourceNodeId));
            sb.append("QueryDom Instruction Execution Request:\n%s\n".formatted(executionRequest.encodePrettily()));
            sb.append("Query Results:\n%s\n".formatted(queryResults.encodePrettily()));
            sb.append("Task Description:\n%s\n".formatted(client.getRequestManager().getActiveExecutionRequest().getTaskDescription()));
            sb.append("Resulting Click Request:\n%s\n".formatted(clickRequest.encodePrettily()));

            bw.write(sb.toString());
            bw.flush();

        }catch(IOException e){
            log.error("Error while saving query dom result!");
            log.error(e.getMessage(), e);

        }
    }
}
