package ca.ualberta.odobot.guidance.connectionmanagers;

import ca.ualberta.odobot.guidance.GuidanceVerticle;
import ca.ualberta.odobot.guidance.OdoClient;
import ca.ualberta.odobot.guidance.WebSocketConnection;
import ca.ualberta.odobot.guidance.feedback.AlternateXpath;
import ca.ualberta.odobot.guidance.feedback.UnresolvableXpath;
import ca.ualberta.odobot.guidance.instructions.Instruction;
import ca.ualberta.odobot.guidance.instructions.MultiStepInstruction;
import io.vertx.core.Context;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;
import java.util.function.Consumer;

public class GuidanceConnectionManager extends AbstractConnectionManager implements ConnectionManager {

    private static final Logger log = LoggerFactory.getLogger(GuidanceConnectionManager.class);
    private static final String SOURCE = "GuidanceConnectionManager";
    private Map<String, Promise> activePromises = new LinkedHashMap<>();

    public long timeoutTimer = -1l;

    public long executionInstructionDelayTimer = -1l;
    public long executionInstructionDelay = 5000l;

    /**
     * The longest an instruction is held for the DOM to settle. On a page that keeps changing, each change would
     * otherwise postpone the next instruction again, until the task times out.
     */
    public long executionInstructionMaxDelay = 30000l;

    /**
     * When ({@link System#nanoTime()}) the current wait for the DOM to settle began, or -1 if there is none.
     */
    private long executionInstructionDelaySince = -1l;


    private JsonObject executionInstruction = null;

    private void printActivePromises(){
        log.info("ActivePromises:");
        activePromises.forEach((key,v)->log.info("{}:{}", key,v));
    }

    /**
     * The context this socket's messages are handled on. Agent logic runs on it as well.
     */
    private Context context = null;

    public GuidanceConnectionManager(OdoClient client){
        super(client);
    }

    @Override
    public void updateConnection(WebSocketConnection connection) {
        super.updateConnection(connection);
        context = Vertx.currentContext();
    }

    public void onMessage(JsonObject message){
        switch (message.getString("type")){
            case "NAVIGATION_OPTIONS_SHOW_RESULT":
                Promise promise = activePromises.get("NAVIGATION_OPTIONS_SHOW_RESULT");
                promise.complete(message);
                activePromises.remove("NAVIGATION_OPTIONS_SHOW_RESULT");
                break;
            case "PATH_COMPLETE_ACK":
                activePromises.get("PATH_COMPLETE_ACK").complete(message);
                activePromises.remove("PATH_COMPLETE_ACK");
                super.addHistory(message);
                break;
            case  "EXECUTION_RESULT":
                printActivePromises();
                // Capture the promise object currently associated with the awaitng execution result.
                final Promise _promise = activePromises.get("EXECUTION_RESULT");
                // Let any listeners know that the execution result they're waiting for is complete.
                activePromises.get("EXECUTION_RESULT").complete(message);
                if (_promise == activePromises.get("EXECUTION_RESULT")){
                    // If those listeners replaced the execution result promise with some new object, don't remove it.
                    // But if the listeners didn't touch the execution result promise go ahead and remove it now.
                    activePromises.remove("EXECUTION_RESULT");
                }
                super.addHistory(message);
                break;

            case "UNRESOLVABLE_XPATH":
                log.info("OdoX reported unresolvable xpath: {} from instruction generated by path node: {}. Attempting to back-track and recover.", message.getString("xpath"), message.getString("sourceNodeId"));
                var failedNodeId = message.getString("sourceNodeId");

                log.info("{}", message.encodePrettily());
                super.addHistory(message);
                client.getRequestManager().onObservation(new UnresolvableXpath(message.getString("xpath"), failedNodeId));


                break;
            case "REGISTER_ALTERNATE_XPATH":
                //During the execution of certain instructions, the exact xpath sent to OdoX by the server might differ from the one OdoX had to use to actually execute the instruction.
                //When this happens, the agent adds the new xpath OdoX used to the corresponding instruction so that it can properly identify that the expected instruciton was executed.
                //TODO: eventually, these new xpaths should be merged into the nav model.
                String alternateXpath = message.getString("alternateXpath");
                String sourceNodeId = message.getString("sourceNodeId");

                log.info("OdoX reported alternate xpath: {} for sourceNodeId: {}", alternateXpath, sourceNodeId);
                client.getRequestManager().onObservation(new AlternateXpath(alternateXpath, sourceNodeId));

                super.addHistory(message);

                JsonObject confirmation = new JsonObject()
                        .put("type", "ALTERNATE_XPATH_CONFIRMED")
                        .put("source", SOURCE)
                        .put("pathsRequestId", client.getRequestManager().getExecutionId().toString())
                        .put("alternateXpath", alternateXpath); //Confirm which xpath was registered.
                send(confirmation);

                break;
        }
    }

    public Future<JsonObject> clearNavigationOptions(){
        JsonObject clearNavigationOptionsRequest = new JsonObject()
                .put("type", "CLEAR_NAVIGATION_OPTIONS")
                .put("source", SOURCE)
                .put("pathsRequestId", client.getRequestManager().getExecutionId().toString());

        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("CLEAR_NAVIGATION_OPTIONS_RESULT", promise);
        printActivePromises();

        send(clearNavigationOptionsRequest);

        return promise.future();
    }

    public Future<JsonObject> notifyPathComplete(){
        JsonObject notifyPathCompleteRequest = makeNotifyPathCompleteRequest(SOURCE);
        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("PATH_COMPLETE_ACK", promise);
        printActivePromises();

        send(notifyPathCompleteRequest);
        return promise.future();
    }

    public Future<JsonObject> showNavigationOptions(JsonObject navigationOptions){
        JsonObject showNavigationOptionsRequest = new JsonObject()
                .put("type", "SHOW_NAVIGATION_OPTIONS")
                .put("source", SOURCE)
                .put("pathsRequestId", client.getRequestManager().getExecutionId().toString())
                .mergeIn(navigationOptions);

        Promise<JsonObject> promise = Promise.promise();
        activePromises.put("NAVIGATION_OPTIONS_SHOW_RESULT", promise);
        printActivePromises();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        send(showNavigationOptionsRequest);

        return promise.future();
    }

    /**
     * @param waitedMs how long the current wait for the DOM to settle has lasted.
     * @return how much longer to wait: the settle delay, cut short so the whole wait never exceeds the max delay.
     */
    static long settleDelay(long waitedMs, long delayMs, long maxDelayMs){
        return Math.max(1, Math.min(delayMs, maxDelayMs - waitedMs));
    }

    /**
     * Hold the next execution instruction until the DOM has not changed for {@link #executionInstructionDelay}, but
     * no longer than {@link #executionInstructionMaxDelay} after the wait began.
     */
    public void resetExecutionInstructionDelay(){
        if(executionInstructionDelayTimer != -1l){
            GuidanceVerticle._vertx.cancelTimer(executionInstructionDelayTimer);
        }

        long now = System.nanoTime();
        if(executionInstructionDelaySince == -1l){
            executionInstructionDelaySince = now;
        }
        long waitedMs = (now - executionInstructionDelaySince) / 1_000_000;
        long delay = settleDelay(waitedMs, executionInstructionDelay, executionInstructionMaxDelay);

        if(delay < executionInstructionDelay){
            log.info("DOM is still changing after {} ms, the next execution instruction will be sent in at most {} ms.", waitedMs, delay);
        }else{
            log.info("Next execution instruction will be delayed to give time for DOM to settle.");
        }
        executionInstructionDelayTimer = GuidanceVerticle._vertx.setTimer(delay, id->{
            executionInstructionDelayTimer = -1;
            executionInstructionDelaySince = -1;
            if(executionInstruction != null){
                log.info("Delayed instruction is being sent now!");
                super.addHistory(executionInstruction);
                super.send(executionInstruction);
                executionInstruction = null;
            }

        });
    }

    /**
     * (Re)start the task timeout. The task fails if the timeout elapses before the next reset.
     */
    public void resetTimeout(){
        //Keep the timeout on the event loop that runs the agent, so the two never run concurrently.
        if(context != null && Vertx.currentContext() != context){
            context.runOnContext(v->resetTimeout());
            return;
        }

        if(timeoutTimer != -1l){ //Only if it hasn't yet been set.
            GuidanceVerticle._vertx.cancelTimer(timeoutTimer);
        }

        timeoutTimer = GuidanceVerticle._vertx.setTimer(client.getRequestManager().getTimeout(), id->{
            //timeoutTimer = id;
            log.info("Task execution timed out!");
            client.getRequestManager().getEvaluationComplete().tryFail("Timeout!");
        });
    }

    /**
     * Send an instruction to OdoX for execution.
     *
     * @param instruction the instruction to execute.
     * @param followUp true if the instruction was produced by the follow-up logic of a {@link MultiStepInstruction}.
     *                 Follow-ups do not reset the task timeout, and are sent after a shorter pause.
     * @param next if the instruction is a {@link MultiStepInstruction}, receives the follow-up instructions it produces
     *             from its EXECUTION_RESULT.
     * @return a future that completes with the EXECUTION_RESULT for the instruction.
     */
    public Future<JsonObject> sendExecutionInstruction(Instruction instruction, boolean followUp, Consumer<Instruction> next){

        if(!followUp){
            resetTimeout();
        }

        JsonObject executionRequest = new JsonObject()
                .put("type", "EXECUTE")
                .put("source", SOURCE)
                .put("executionId", client.getRequestManager().getExecutionId().toString())
                .mergeIn(instruction.toJson());

        Promise<JsonObject> promise = Promise.promise();

        //Multi-step instructions produce follow-up instructions from their execution result.
        if(instruction instanceof MultiStepInstruction multiStepInstruction){
            log.info("Configuring handling the response for {} instruction.", executionRequest.getString("action"));

            promise.future()
                    .onFailure(err->log.error(err.getMessage(), err))
                    .onSuccess(response->multiStepInstruction.onExecutionResult(executionRequest, response, next));
        }

        log.info("Added EXECUTION_RESULT promise.");
        activePromises.put("EXECUTION_RESULT", promise);
        printActivePromises();
        try{
            Thread.sleep(followUp?1000:3000);
        }catch (InterruptedException e){
            throw new RuntimeException(e);
        }
        send(executionRequest);

        return promise.future();
    }

    protected boolean send(JsonObject data){
        if(executionInstructionDelayTimer == -1l || (data.containsKey("type") && !data.getString("type").equals("EXECUTE"))){
            log.info("No delay for instruction, sending immediately.");
            data.put("delayed", false);
            super.addHistory(data);
            return super.send(data);
        }else{
            log.info("Delay requested for instruction, saving instruction to be sent after delay.");
            data.put("delayed", true);
            if(executionInstruction != null){
                log.error("Fatal Error, previous instruction was still waiting to be sent!");
                GuidanceVerticle._vertx.setTimer(executionInstructionDelay, timer->{
                    send(data);
                });
                return false;

            }
            executionInstruction = data;
            return true;
        }

    }

    /**
     * Tells the harness when an EXECUTE message has actually reached OdoX. A message queued while OdoX is disconnected is reported
     * when the connection comes back and the queue is flushed.
     */
    @Override
    protected void onSent(String data){
        if(!data.contains("\"EXECUTE\"")){
            return;
        }
        JsonObject message = new JsonObject(data);
        if("EXECUTE".equals(message.getString("type"))){
            client.getRequestManager().onExecutionInstructionSent(message);
        }
    }

    public void dumpHistory(){
        super.saveHistory(SOURCE);
        super.history.clear();
    }

}
