host: 0.0.0.0
port: 8053
apiPathPrefix: "/api/*"
openAI:
  secretKey: ""
  model: "gpt-5-mini-2025-08-07"
  maxTokens: null
  standardizeDataEntryLabels:
    maxAttempts: 5
    systemPrompt: |
      Below is a numbered list of annotated data entries and their descriptions, they describe the kind of data that was entered into an HTML input box/textarea, TinyMCE content editor, or other data entry widget. 
      Your job is to remove duplicates from the list by combining them and giving them a single standardized name and description. 
      
      
      
      Your output should be a JSON array of JSON objects with the following format:
      ```json
      [
        {
          "standard_name": <standardized name for these semantically similar annotations>
          "annotations": [<list of integers corresponding with the members of this semantic group>]
        }
      ]
      ```
      
      Here is an example:
      
      Input:
      
      1. Message Body 
      2. Message body (rich text content)
      3. Message body (rich text editor) 
      4. Discussion Topic Title 
      5. Discussion topic message (post body) 
      6. Discussion topic message (rich text body) 
      7. Email address (login identifier) 
      8. Message body (rich text) 
      9. Message body (rich text) 
      
      Output:
      
      ```json
      [
        {
          "standard_name": "Message Body",
          "annotations":[1,2,3,8,9]
        },
        {
          "standard_name": "Discussion Topic Message",
          "annotations": [5,6]
        }
      ]
      ```

  generateLabelAndDescription:
    maxAttempts: 5
    systemPrompt: | 
      You are a web data entry analyzer. You are provided with: an HTML element into which data has been entered, this is the input element. A corresponding HTML snippet that contains HTML elements near the input element. As well as one or more examples of the kind of data that was entered if this is available. Your task is to produce a label that describes the semantic role of the entered data in the context of the web application. Additionally produce one sentence describing what the entered data is used for, this will be the description. 
      If you are producing a label and description for a radio button, instead of focusing on the semantics of the selected button, focus the label and description on the semantics of the radio group as a whole. 
      
      Your output should be of the form: 
      Label:
      `<label output>` 
      Description: 
      `<description output>`