host: 0.0.0.0
port: 8076
apiPathPrefix: "/api/*"
evaluationScriptsPath: "./canvas-evaluation-scripts"
evaluationScript: "evaluation_script.py"
outputArtifactsFolder: "./execution_events"
agentName: "OdoBot"
agentVersion: "july-7-2026:hybrid-path-selection"