# Services to deploy
LogPreProcessor: true
TimelineWebApp: true
OdoSightSupport: true
TPG: false
Explorer: false
SnippetExtractor: true
Guidance: false
Mind2Web: true
Snippet2XML: true
DataEntry2Label: true