host: 0.0.0.0
port: 8055
odoLshHost: "127.0.0.1"
odoLshPort: 5000
apiPathPrefix: "/api/*"
sqliteVectorConfig:
  databasePath: "odobot.db"
  extensionPath: "libs/vector"
  embeddingModel: "text-embedding-3-large"
  syntheticTaskVectorTable: 'synthetic_task_vectors'
  distance: "L2" #Options are  distance=L1, distance=L2, distance=COSINE, distance=DOT, distance=SQUARED_L2, or distance=HAMMING
  dimensions: 3072
  type: "FLOAT32"
  secretKey: ""
openAI:
  secretKey: ""
  model: "gpt-5-mini-2025-08-07"
  generateSyntheticTaskForTrajectory:
    maxAttempts: 3
    systemPrompt: |
      You are an intelligent observer/auditor learning how to use a web application by watching how others interact with it. You will be given a history of events that have been observed on the web application. Your task is to generate a plausible description of a task that led to the observed interactions. Write in the imperative style as if you were the author of the task that prompted these interactions. Keep the succinct, no more than a paragraph 2 to 5 sentences long, but make sure to include relevant input values. To keep the task description short, omit task validation instructions.
  generateSemanticLabelForTrajectoryEvent:
    maxAttempts: 3
    systemPrompt: |
      You are an intelligent observer/auditor learning how to use a web application by watching how others interact with it. You will be given a user interaction event. Your task is to describe what happened/was accomplished/was observed in this event in 2 or 3 sentences maximum. Write down anything that you feel would be relevant to you if someone were to ask you what a user did exactly on the web application.
      
      Events rarely occur in isolation, any events leading up to the current event, as well as your notes and descriptions for them will be provided to you as history to help you contextualize the current event.
      
      To sum up, you will be given a history of events leading up to the current event if any exists, as well as the details of the current event. Your task is to produce text describing what happened/was accomplished/was observed in the event. Focus on what new information the current event brings to the table in context of the available history, do not repeat information that already exists in the history.
  generateLinkLabel:
    maxAttempts: 3
    systemPrompt: |
      You will be given the raw and normalized value of an 'href' attribute harvested from an <a> HTML tag of a web application. Your task is to determine if the link points to specific single instance of a resource, and if so, return the type of the resource being linked and nothing else. 
      If the link does not appear to lead to an instance  of a resource return 'Does not link to a specific resource.' and nothing else. 
      
      Here are some examples:
      
      Example Input 1: 
      raw href: /courses/2/announcements/17 normalized href: /courses/*/announcements/*
      
      Example Output 1:
      Announcement
      
      Example Input 2: 
      raw href: /courses/1/quizzes/4  normalized href: /courses/*/quizzes/*
      
      Example Output 2:
      Quiz
      
      Example Input 3:
      raw href: /dashboard/data_exports normalized href: /dashboard/data_exports
      
      Example Output 3:
      Does not link to a specific resource.
      
      Example Input 3:
      raw href: /about/14 normalized href: /about/*
        
      Example Output 4:
      Does not link to a specific resource.

  generateStateClusterLabel:
    maxSnapshots: 3
    maxAttempts: 3
    systemPrompt: |
      Below are some sample HTML documents which have been identified as structurally similar. They represent a logical state/page of a web application. Your task is to produce a short meaningful natural language label for the general application state. The labels should be generalized, avoid labels that make direct references to specific content on the page. 
      For example "Edit Introduction to Psychology 101 Page" would be a bad label since it is specific to the 'Introduction to Psychology 101' page. A better label would be 'Edit Page'.
      Your output should be the general application state label and nothing else.
