host: 0.0.0.0
port: 8054
apiPathPrefix: "/api/*"
neo4j:
  host: "bolt://localhost:7687"
  user: "neo4j"
  password: "odobotdb"
openAI:
  secretKey: ""
  model: "gpt-4o-mini"
  temperature: null
  topP: 0.01
  maxTokens: null
  getRelevantObjectParameters:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of objects that exist in a web application. Your job is to identify instances of these objects in the description of a task to be completed on the web application. The output should be a list of numbers corresponding with the objects you have identified as relevant and nothing else.
  getInputParameterMappings:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of objects and input values that exist in a web application. Your job is to identify instances of these items in the description of a task to be completed on the web application. The output should be a list of 2-length arrays [input field, value] in valid JSON and nothing else. If you cannot determine an appropriate value for a field, set the value to null.
  getTaskAPICalls:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of API routes that have been captured for a web application. You will also be given a description of a task to be completed on the web application. Your job is to identify which of the API calls would be relevant to the described task. The output should be a list of numbers corresponding with the API routes you have identified as relevant and nothing else.