host: 0.0.0.0
port: 8054
apiPathPrefix: "/api/*"
neo4j:
  host: "bolt://localhost:7687"
  user: "neo4j"
  password: "odobotdb"
openAI:
  secretKey: ""
  model: "gpt-4o"
  temperature: null
  topP: 0.01
  maxTokens: null
  getRelevantObjectParameters:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of objects that exist in a web application. Your job is to identify instances of these items in the description of a task to be completed on the web application. The output should be a list of 2-length arrays [input field, value] in valid JSON and nothing else. If you cannot determine an appropriate value for a field, set the value to null.
  getInputParameterMappings:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of objects and input values that exist in a web application. Your job is to identify instances of these items in the description of a task to be completed on the web application. The output should be a list of 2-length arrays [input field, value] in valid JSON and nothing else. If you cannot determine an appropriate value for a field, set the value to null.
  getTaskAPICalls:
    maxAttempts: 5
    systemPrompt: |
      What follows is a list of API routes that have been captured for a web application. You will also be given a description of a task to be completed on the web application. Your job is to identify one single API route, that best characterizes the intent of the task. The output should be a single number corresponding with the API route you have identified and nothing else.
  selectPath:
    maxAttempts: 5
    systemPrompt: |
      You are meant to complete the following task on a web application: 
      
      %s
      
      What follows is a list of possible paths to achieving the above task on the web application. Each path has an ID and a list of interactions to be applied to the web application. Your job is to select the ID of the path that best fits the description of the task above. The output should be the ID of the selected path an nothing else.